import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Aside } from "@/components/_ui/aside";
import { MainTitle } from "@/components/_ui/mainTitle";

import StyledComponentsRegistry from "../lib/AntdRegistry";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quadro de Anúncios",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html>
        <body className={`${inter.className}`}>
          <div className="template">
            <div className="sidenav">
              <Aside />
            </div>
               <main className="content">
              <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
            </main>
            <footer className="footer"></footer>
          </div>
        </body>
      </html>
    </>
  );
}
